package generator

import (
	"fmt"
	"strings"

	"github.com/smoxy-io/proto2fixed/pkg/analyzer"
	"github.com/smoxy-io/proto2fixed/pkg/parser"
)

const (
	LangArduino Language = "arduino"
)

// ArduinoGenerator generates C/C++ code for Arduino/ESP32
type ArduinoGenerator struct{}

// NewArduinoGenerator creates a new Arduino generator
func NewArduinoGenerator() *ArduinoGenerator {
	return &ArduinoGenerator{}
}

// Generate generates Arduino/C++ header file
func (g *ArduinoGenerator) Generate(schema *parser.Schema, layouts map[string]*analyzer.MessageLayout) (string, error) {
	var sb strings.Builder

	// Header guard
	guardName := strings.ToUpper(strings.ReplaceAll(schema.FileName, ".", "_")) + "_BINARY_H"
	sb.WriteString(fmt.Sprintf("// Generated from %s\n", schema.FileName))
	sb.WriteString("// DO NOT EDIT - Auto-generated by proto2fixed\n")
	sb.WriteString(fmt.Sprintf("// Schema Version: %s\n", schema.Version))
	sb.WriteString(fmt.Sprintf("// Endianness: %s\n", schema.Endian))

	// Check if any message has IDs
	hasMessageIds := false
	for _, layout := range layouts {
		if layout.HasMessageId {
			hasMessageIds = true
			break
		}
	}

	if hasMessageIds {
		sb.WriteString(fmt.Sprintf("// Message ID Size: %d bytes\n", schema.MessageIdSize))
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("#ifndef %s\n", guardName))
	sb.WriteString(fmt.Sprintf("#define %s\n\n", guardName))

	// Includes
	sb.WriteString("#include <stdint.h>\n")
	sb.WriteString("#include <stdbool.h>\n")
	sb.WriteString("#include <string.h>\n\n")

	// Generate MessageId typedef if any message has IDs
	if hasMessageIds {
		typedefType := ""
		switch schema.MessageIdSize {
		case 1:
			typedefType = "uint8_t"
		case 2:
			typedefType = "uint16_t"
		case 4:
			typedefType = "uint32_t"
		case 8:
			typedefType = "uint64_t"
		}
		sb.WriteString("// Message Header for messages with IDs\n")
		sb.WriteString(fmt.Sprintf("// All message IDs are %d byte(s)\n", schema.MessageIdSize))
		sb.WriteString(fmt.Sprintf("typedef %s MessageId;\n\n", typedefType))
	}

	// Disable structure padding
	sb.WriteString("#pragma pack(push, 1)  // Disable structure padding\n\n")

	// Generate enums
	for _, enum := range schema.Enums {
		g.generateEnum(&sb, enum)
	}

	// Generate message ID constants
	if hasMessageIds {
		sb.WriteString("// Message IDs\n")
		for _, msg := range schema.Messages {
			layout := layouts[msg.Name]
			if layout.HasMessageId {
				sb.WriteString(fmt.Sprintf("#define MSGID_%s %d\n",
					strings.ToUpper(toSnakeCase(msg.Name)), layout.MessageId))
			}
		}
		sb.WriteString("\n")
	}

	// Generate messages
	for _, msg := range schema.Messages {
		layout, exists := layouts[msg.Name]
		if !exists {
			return "", fmt.Errorf("layout not found for message: %s", msg.Name)
		}
		g.generateMessage(&sb, msg, layout, layouts)
	}

	// Restore structure padding
	sb.WriteString("#pragma pack(pop)\n\n")

	// Generate static assertions
	sb.WriteString("// Compile-time size validation\n")
	for _, msg := range schema.Messages {
		layout := layouts[msg.Name]
		sb.WriteString(fmt.Sprintf("static_assert(sizeof(%s) == %d, \"%s size mismatch\");\n",
			msg.Name, layout.TotalSize, msg.Name))
	}
	sb.WriteString("\n")

	// Generate encode/decode functions
	for _, msg := range schema.Messages {
		layout := layouts[msg.Name]
		g.generateEncodeDecode(&sb, msg, layout, schema)
	}

	// Generate string helper
	g.generateStringHelper(&sb)

	// Generate embedded JSON schema (if messages exist)
	if len(schema.Messages) > 0 {
		sb.WriteString("// Embedded JSON schema (for discovery response)\n")
		for _, msg := range schema.Messages {
			sb.WriteString(fmt.Sprintf("extern const char %s_SCHEMA[];\n", strings.ToUpper(msg.Name)))
		}
		sb.WriteString("\n")
	}

	// Close header guard
	sb.WriteString(fmt.Sprintf("#endif // %s\n", guardName))

	return sb.String(), nil
}

func (g *ArduinoGenerator) generateEnum(sb *strings.Builder, enum *parser.Enum) {
	sb.WriteString(fmt.Sprintf("// %s enum (%d byte(s))\n", enum.Name, enum.Size))

	sb.WriteString(fmt.Sprintf("typedef enum {\n"))
	for _, val := range enum.Values {
		sb.WriteString(fmt.Sprintf("  %s = %d,\n", val.Name, val.Number))
	}
	sb.WriteString(fmt.Sprintf("} %s;\n\n", enum.Name))
}

func (g *ArduinoGenerator) generateMessage(sb *strings.Builder, msg *parser.Message, layout *analyzer.MessageLayout, layouts map[string]*analyzer.MessageLayout) {
	sb.WriteString(fmt.Sprintf("// %s message (%d bytes)\n", msg.Name, layout.TotalSize))

	if msg.Union {
		sb.WriteString("typedef union {\n")
		if layout.HasDiscriminator {
			sb.WriteString("  uint8_t _discriminator;  // Field number of active variant\n")
		}
	} else {
		sb.WriteString("typedef struct {\n")
	}

	// Track current offset for padding
	currentOffset := uint32(0)
	paddingIndex := 0

	// Interleave regular fields and oneofs based on offset
	fieldIdx := 0
	oneofIdx := 0

	for fieldIdx < len(layout.Fields) || oneofIdx < len(layout.Oneofs) {
		// Determine whether to place a field or oneof next
		placeField := true
		if fieldIdx >= len(layout.Fields) {
			placeField = false
		} else if oneofIdx < len(layout.Oneofs) {
			if layout.Oneofs[oneofIdx].Offset < layout.Fields[fieldIdx].Offset {
				placeField = false
			}
		}

		if placeField {
			// Place regular field
			fieldLayout := layout.Fields[fieldIdx]
			field := fieldLayout.Field

			// Add padding if needed
			if !msg.Union && fieldLayout.Offset > currentOffset {
				paddingSize := fieldLayout.Offset - currentOffset
				sb.WriteString(fmt.Sprintf("  uint8_t _padding_%d[%d];  // Padding: %d-%d\n",
					paddingIndex, paddingSize, currentOffset, fieldLayout.Offset-1))
				paddingIndex++
				currentOffset = fieldLayout.Offset
			}

			// Field comment
			sb.WriteString(fmt.Sprintf("  // Field %d, Offset: %d, Size: %d\n",
				field.Number, fieldLayout.Offset, fieldLayout.Size))

			// Field definition
			typeName := getTypeNameC(field)
			fieldName := toSnakeCase(field.Name)

			if field.Type == parser.TypeString {
				sb.WriteString(fmt.Sprintf("  char %s[%d];  // null-terminated\n",
					fieldName, field.StringSize))
			} else if field.Repeated || (field.Type == parser.TypeBytes && field.ArraySize > 0) {
				// Repeated fields or bytes fields with fixed array size
				sb.WriteString(fmt.Sprintf("  %s %s[%d];\n",
					typeName, fieldName, field.ArraySize))
			} else {
				sb.WriteString(fmt.Sprintf("  %s %s;\n",
					typeName, fieldName))
			}

			currentOffset = fieldLayout.Offset + fieldLayout.Size
			fieldIdx++
		} else {
			// Place oneof
			oneofLayout := layout.Oneofs[oneofIdx]

			// Add padding if needed
			if !msg.Union && oneofLayout.Offset > currentOffset {
				paddingSize := oneofLayout.Offset - currentOffset
				sb.WriteString(fmt.Sprintf("  uint8_t _padding_%d[%d];  // Padding: %d-%d\n",
					paddingIndex, paddingSize, currentOffset, oneofLayout.Offset-1))
				paddingIndex++
				currentOffset = oneofLayout.Offset
			}

			// Oneof comment
			sb.WriteString(fmt.Sprintf("  // Oneof %s, Offset: %d, Size: %d\n",
				oneofLayout.Oneof.Name, oneofLayout.Offset, oneofLayout.Size))

			// Generate union for oneof
			oneofName := toSnakeCase(oneofLayout.Oneof.Name)
			sb.WriteString(fmt.Sprintf("  union {\n"))
			sb.WriteString(fmt.Sprintf("    uint8_t _discriminator;  // Field number of active variant\n"))

			for _, variantLayout := range oneofLayout.Fields {
				variant := variantLayout.Field
				typeName := getTypeNameC(variant)
				variantName := toSnakeCase(variant.Name)

				if variant.Type == parser.TypeString {
					sb.WriteString(fmt.Sprintf("    char %s[%d];  // null-terminated\n",
						variantName, variant.StringSize))
				} else if variant.Repeated {
					sb.WriteString(fmt.Sprintf("    %s %s[%d];\n",
						typeName, variantName, variant.ArraySize))
				} else {
					sb.WriteString(fmt.Sprintf("    %s %s;\n",
						typeName, variantName))
				}
			}

			sb.WriteString(fmt.Sprintf("  } %s;\n", oneofName))

			currentOffset = oneofLayout.Offset + oneofLayout.Size
			oneofIdx++
		}
	}

	// Add final padding if needed
	if !msg.Union && currentOffset < layout.TotalSize {
		paddingSize := layout.TotalSize - currentOffset
		sb.WriteString(fmt.Sprintf("  uint8_t _padding_%d[%d];  // Padding: %d-%d\n",
			paddingIndex, paddingSize, currentOffset, layout.TotalSize-1))
	}

	sb.WriteString(fmt.Sprintf("} %s;\n\n", msg.Name))
}

func (g *ArduinoGenerator) generateEncodeDecode(sb *strings.Builder, msg *parser.Message, layout *analyzer.MessageLayout, schema *parser.Schema) {
	if layout.HasMessageId {
		// Encode with message ID header
		sb.WriteString(fmt.Sprintf("// Encode %s with message ID header (%d bytes total: %d header + %d body)\n",
			msg.Name, layout.MessageTotalSize, layout.MessageIdSize, layout.TotalSize))
		sb.WriteString(fmt.Sprintf("inline void encode%s(const %s* msg, uint8_t* buffer) {\n",
			msg.Name, msg.Name))
		sb.WriteString(fmt.Sprintf("  *(MessageId*)buffer = (MessageId)%d; // messageId\n", layout.MessageId))
		sb.WriteString(fmt.Sprintf("  memcpy(buffer + %d, msg, sizeof(%s));\n", layout.MessageIdSize, msg.Name))
		sb.WriteString("}\n\n")

		// Decode with message ID verification
		sb.WriteString(fmt.Sprintf("// Decode %s (verifies message ID)\n", msg.Name))
		sb.WriteString(fmt.Sprintf("inline bool decode%s(const uint8_t* buffer, %s* msg) {\n",
			msg.Name, msg.Name))
		sb.WriteString("  // Verify message ID\n")
		sb.WriteString(fmt.Sprintf("  if (*(MessageId*)buffer != %d) return false;\n", layout.MessageId))
		sb.WriteString(fmt.Sprintf("  memcpy(msg, buffer + %d, sizeof(%s));\n", layout.MessageIdSize, msg.Name))
		sb.WriteString("  return true;\n")
		sb.WriteString("}\n\n")
	} else {
		// Encode function without header
		sb.WriteString(fmt.Sprintf("// Encode function (simple memcpy for binary data)\n"))
		sb.WriteString(fmt.Sprintf("inline void encode%s(const %s* msg, uint8_t* buffer) {\n",
			msg.Name, msg.Name))
		sb.WriteString(fmt.Sprintf("  memcpy(buffer, msg, sizeof(%s));\n", msg.Name))
		sb.WriteString("}\n\n")

		// Decode function without verification
		sb.WriteString(fmt.Sprintf("// Decode function (simple memcpy for binary data)\n"))
		sb.WriteString(fmt.Sprintf("inline void decode%s(const uint8_t* buffer, %s* msg) {\n",
			msg.Name, msg.Name))
		sb.WriteString(fmt.Sprintf("  memcpy(msg, buffer, sizeof(%s));\n", msg.Name))
		sb.WriteString("}\n\n")
	}
}

func (g *ArduinoGenerator) generateStringHelper(sb *strings.Builder) {
	sb.WriteString("// String helper: safely copy string to fixed-size field\n")
	sb.WriteString("inline void setFixedString(char* dest, size_t dest_size, const char* src) {\n")
	sb.WriteString("  strncpy(dest, src, dest_size - 1);\n")
	sb.WriteString("  dest[dest_size - 1] = '\\0';  // Ensure null termination\n")
	sb.WriteString("}\n\n")
}
