package generator

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/smoxy-io/proto2fixed/pkg/analyzer"
	"github.com/smoxy-io/proto2fixed/pkg/parser"
)

const (
	LangGo Language = "go"
)

// GoGenerator generates Go decoder/encoder code
type GoGenerator struct {
	packageName    string
	constants      map[string]string
	helpersName    string
	helpersVarName string
}

func (g *GoGenerator) setNames(prefix string) {
	if prefix == "" {
		return
	}

	camelPrefix := toCamelCase(prefix)

	g.helpersName = camelPrefix + "Helpers"
	g.helpersVarName = initialsFromCamelCase(camelPrefix) + "H"
}

// NewGoGenerator creates a new Go generator
func NewGoGenerator() *GoGenerator {
	return &GoGenerator{}
}

// Generate generates Go code
func (g *GoGenerator) Generate(schema *parser.Schema, layouts map[string]*analyzer.MessageLayout) (string, error) {
	var sb strings.Builder

	// get the capitalized base filename without extension to prevent collisions
	capFilename := schema.BaseFilenameWithoutExt(true)

	g.setNames(schema.BaseFilenameWithoutExt(false))
	g.packageName = schema.GoPackage

	// Determine byte order
	byteOrder := "binary.LittleEndian"

	if schema.Endian == "big" {
		byteOrder = "binary.BigEndian"
	}

	// Package and imports
	sb.WriteString("// Code generated by proto2fixed. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// source: %s\n\n", schema.FileName))
	sb.WriteString(fmt.Sprintf("package %s\n\n", schema.GoPackage))
	sb.WriteString("import (\n")
	sb.WriteString("\t\"encoding/binary\"\n")
	sb.WriteString("\t\"encoding/json\"\n")
	sb.WriteString("\t\"fmt\"\n")

	if schema.HasType(parser.TypeFloat, parser.TypeDouble) {
		sb.WriteString("\t\"math\"\n")
	}

	sb.WriteString(")\n\n")

	// Check if any message has IDs
	hasMessageIds := false

	for _, layout := range layouts {
		if layout.HasMessageId {
			hasMessageIds = true
			break
		}
	}

	g.constants = map[string]string{
		"schemaVersion": capFilename + "SchemaVersion",
		"schemaEndian":  capFilename + "SchemaEndian",
		"messageIdSize": capFilename + "MessageIdSize",
	}

	// Generate schema metadata constants
	sb.WriteString("// Schema metadata\n")
	sb.WriteString(fmt.Sprintf("const %s = \"%s\"\n", g.constants["schemaVersion"], schema.Version))
	sb.WriteString(fmt.Sprintf("const %s = \"%s\"\n", g.constants["schemaEndian"], schema.Endian))

	if hasMessageIds {
		sb.WriteString(fmt.Sprintf("const %s = %d\n", g.constants["messageIdSize"], schema.MessageIdSize))
	}

	sb.WriteString("\n")

	// Generate message size constants
	for _, msg := range schema.Messages {
		layout := layouts[msg.Name]

		sb.WriteString(fmt.Sprintf("// %s Message Definitions\n\n", msg.Name))

		g.constants[msg.Name+"Size"] = msg.Name + "Size"

		sb.WriteString(fmt.Sprintf("// %sSize is the fixed binary size\n", msg.Name))
		sb.WriteString(fmt.Sprintf("const %s = %d\n", g.constants[msg.Name+"Size"], layout.TotalSize))

		if layout.HasMessageId {
			g.constants[msg.Name+"MessageId"] = msg.Name + "MessageId"

			sb.WriteString(fmt.Sprintf("// %sMessageId is the size of the message ID\n", msg.Name))

			sb.WriteString(fmt.Sprintf("const %s = %d\n", g.constants[msg.Name+"MessageId"], layout.MessageId))

			sb.WriteString("\n")

			// generate decoder
			g.generateDecoder(&sb, msg, layout, layouts, byteOrder)

			// generate encoder
			g.generateEncoder(&sb, msg, layout, layouts, byteOrder)
		}

		sb.WriteString("\n")
	}

	//// Generate registry if message IDs are used
	//if hasMessageIds {
	//	g.generateRegistry(&sb, schema, layouts, byteOrder)
	//}

	// Generate helper functions
	g.generateHelpers(&sb)

	// format generated code
	fmtString, fsErr := format.Source([]byte(sb.String()))

	if fsErr != nil {
		return "", fsErr
	}

	return string(fmtString), nil
}

func (g *GoGenerator) generateDecoder(sb *strings.Builder, msg *parser.Message, layout *analyzer.MessageLayout, layouts map[string]*analyzer.MessageLayout, byteOrder string) {
	decoderName := fmt.Sprintf("%sDecoder", msg.Name)

	sb.WriteString(fmt.Sprintf("// %s decodes binary data to JSON\n", decoderName))
	sb.WriteString(fmt.Sprintf("type %s struct {\n", decoderName))
	sb.WriteString("\tendian binary.ByteOrder\n")
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("// New%s creates a new decoder\n", decoderName))
	sb.WriteString(fmt.Sprintf("func New%s() *%s {\n", decoderName, decoderName))
	sb.WriteString(fmt.Sprintf("\treturn &%s{\n", decoderName))
	sb.WriteString(fmt.Sprintf("\t\tendian: %s,\n", byteOrder))
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// Decode method
	sb.WriteString(fmt.Sprintf("// Decode decodes binary data to JSON string\n"))
	sb.WriteString(fmt.Sprintf("func (d *%s) Decode(data []byte) ([]byte, error) {\n", decoderName))
	sb.WriteString(fmt.Sprintf("\tif len(data) != %s {\n", g.constants[msg.Name+"Size"]))
	sb.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"invalid data size: got %%d, want %%d\", len(data), %s)\n", g.constants[msg.Name+"Size"]))
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tresult := make(map[string]any)\n")

	// Handle union discriminator
	if msg.Union && layout.HasDiscriminator {
		sb.WriteString("\n\t// Union discriminator\n")
		sb.WriteString(fmt.Sprintf("\tdiscriminator := data[%d]\n\n", layout.DiscriminatorOffset))

		// Generate switch for each field
		sb.WriteString("\tswitch discriminator {\n")
		sb.WriteString("\tcase 0:\t\t// No field set. skip\n")
		sb.WriteString("\t\tbreak\n\n")

		for _, fieldLayout := range layout.Fields {
			sb.WriteString(fmt.Sprintf("\tcase %d:\t\t// %s\n", fieldLayout.Field.Number, fieldLayout.Field.Name))

			g.generateFieldDecoder(sb, fieldLayout, layouts, "data", "result", 0)
		}

		sb.WriteString("\tdefault:\n")
		sb.WriteString("\t\treturn nil, fmt.Errorf(\"unknown discriminator value: %d\", discriminator)\n")
		sb.WriteString("\t}\n\n")
		sb.WriteString("\treturn json.Marshal(result)\n")
		sb.WriteString("}\n\n")

		return
	}

	// Decode fields (non-union)
	for _, fieldLayout := range layout.Fields {
		sb.WriteString("\n")
		g.generateFieldDecoder(sb, fieldLayout, layouts, "data", "result", 0)
	}

	// Decode oneofs
	for _, oneofLayout := range layout.Oneofs {
		sb.WriteString(fmt.Sprintf("\n\t// Oneof %s (offset: %d, size: %d)\n",
			oneofLayout.Oneof.Name, oneofLayout.Offset, oneofLayout.Size))
		sb.WriteString(fmt.Sprintf("\tdiscriminator := data[%d]\n", oneofLayout.DiscriminatorOffset))
		sb.WriteString(fmt.Sprintf("\t%sOneof := make(map[string]any)\n\n", oneofLayout.Oneof.Name))
		sb.WriteString("\tswitch discriminator {\n")
		sb.WriteString("\tcase 0:\t\t// No field set. skip\n")
		sb.WriteString("\t\tbreak\n\n")

		for _, variantLayout := range oneofLayout.Fields {
			sb.WriteString(fmt.Sprintf("\tcase %d:\t\t// %s\n", variantLayout.Field.Number, variantLayout.Field.Name))

			g.generateFieldDecoder(sb, variantLayout, layouts, "data", oneofLayout.Oneof.Name+"Oneof", 1)

			sb.WriteString("\n")
		}

		sb.WriteString("\tdefault:\n")
		sb.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"oneof %s: unknown discriminator value: %%d\", discriminator)\n", oneofLayout.Oneof.Name))
		sb.WriteString("\t}\n\n")

		oneofName := toCamelCase(oneofLayout.Oneof.Name)

		sb.WriteString(fmt.Sprintf("\tresult[\"%s\"] = %sOneof\n", oneofName, oneofLayout.Oneof.Name))
	}

	sb.WriteString("\n\treturn json.Marshal(result)\n")
	sb.WriteString("}\n\n")
}

func (g *GoGenerator) generateFieldDecoder(sb *strings.Builder, fieldLayout *analyzer.FieldLayout, layouts map[string]*analyzer.MessageLayout, dataVar, resultVar string, depth int) {
	baseIndent := strings.Repeat("\t", depth)

	field := fieldLayout.Field
	offset := fieldLayout.Offset
	fieldName := toCamelCase(field.Name)

	if field.Repeated && field.Type == parser.TypeMessage && field.MessageType != nil {
		// Array of messages
		elemSize := fieldLayout.Size / field.ArraySize

		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s array (field %d, offset: %d, count: %d, elementSize: %d)\n",
			field.Name, field.Number, offset, field.ArraySize, elemSize))
		sb.WriteString(baseIndent + fmt.Sprintf("\t%sArr := make([]map[string]any, %d)\n\n", field.Name, field.ArraySize))
		sb.WriteString(baseIndent + fmt.Sprintf("\tfor i := 0; i < %d; i++ {\n", field.ArraySize))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\telem := make(map[string]any)\n\n"))

		nestedLayout := layouts[field.MessageType.Name]

		for _, nestedField := range nestedLayout.Fields {
			g.generateFieldDecoder(sb, nestedField, layouts, dataVar, "elem", depth+1)
			sb.WriteString("\n")
		}

		sb.WriteString(baseIndent + fmt.Sprintf("\t\t%sArr[i] = elem\n", field.Name))
		sb.WriteString(baseIndent + "\t}\n\n")
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s[\"%s\"] = %sArr\n", resultVar, fieldName, field.Name))
	} else if field.Repeated {
		// Array of primitives
		elemSize := fieldLayout.Size / field.ArraySize

		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s array (field %d, offset: %d)\n",
			field.Name, field.Number, offset))
		sb.WriteString(baseIndent + fmt.Sprintf("\t%sArr := make([]any, %d)\n", field.Name, field.ArraySize))
		sb.WriteString(baseIndent + fmt.Sprintf("\tfor i := 0; i < %d; i++ {\n", field.ArraySize))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\telemOffset := %d + (i * %d)\n", offset, elemSize))

		g.generatePrimitiveDecoder(sb, field, dataVar, "elemOffset", fmt.Sprintf("%sArr[i]", field.Name), true, baseIndent)

		sb.WriteString(baseIndent + "\t}\n\n")
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s[\"%s\"] = %sArr\n", resultVar, fieldName, field.Name))
	} else if field.Type == parser.TypeMessage && field.MessageType != nil {
		// Nested message
		nestedDataName := fmt.Sprintf("%sNestedData", field.Name)

		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s (field %d, offset: %d, size: %d)\n",
			field.Name, field.Number, offset, fieldLayout.Size))
		sb.WriteString(baseIndent + fmt.Sprintf("\t%sNested := make(map[string]any)\n\n", field.Name))
		sb.WriteString(baseIndent + fmt.Sprintf("\t{\n"))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t%s := %s[%d:%d]\n\n", nestedDataName, dataVar, offset, offset+fieldLayout.Size))

		nestedLayout := layouts[field.MessageType.Name]

		for i, nestedField := range nestedLayout.Fields {
			if i != 0 {
				sb.WriteString("\n")
			}

			g.generateFieldDecoder(sb, nestedField, layouts, nestedDataName, fmt.Sprintf("%sNested", field.Name), depth+1)
		}

		sb.WriteString(baseIndent + "\t}\n\n")
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s[\"%s\"] = %sNested\n", resultVar, fieldName, field.Name))
	} else {
		// Primitive type
		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s (field %d, offset: %d, size: %d)\n",
			field.Name, field.Number, offset, fieldLayout.Size))

		g.generatePrimitiveDecoder(sb, field, dataVar, fmt.Sprintf("%d", offset), fmt.Sprintf("%s[\"%s\"]", resultVar, fieldName), false, baseIndent)
	}
}

func (g *GoGenerator) generatePrimitiveDecoder(sb *strings.Builder, field *parser.Field, dataVar, offsetExpr, targetVar string, useIndex bool, baseIndent string) {
	var offsetEnd string

	offsetStart := offsetExpr

	if useIndex {
		switch field.Type {
		case parser.TypeBool:
			offsetEnd = offsetExpr + "+1"
		case parser.TypeInt32, parser.TypeUint32, parser.TypeFloat:
			offsetEnd = offsetExpr + "+4"
		case parser.TypeInt64, parser.TypeUint64, parser.TypeDouble:
			offsetEnd = offsetExpr + "+8"
		case parser.TypeEnum:
			if field.EnumType != nil {
				offsetEnd = fmt.Sprintf("%s+%d", offsetExpr, field.EnumType.Size)
			} else {
				offsetEnd = offsetExpr + "+4"
			}
		}
	} else {
		switch field.Type {
		case parser.TypeBool:
			offsetEnd = fmt.Sprintf("%s+1", offsetExpr)
		case parser.TypeInt32, parser.TypeUint32, parser.TypeFloat:
			offsetEnd = fmt.Sprintf("%s+4", offsetExpr)
		case parser.TypeInt64, parser.TypeUint64, parser.TypeDouble:
			offsetEnd = fmt.Sprintf("%s+8", offsetExpr)
		case parser.TypeString:
			offsetEnd = fmt.Sprintf("%s+%d", offsetExpr, field.StringSize)
		case parser.TypeEnum:
			if field.EnumType != nil {
				offsetEnd = fmt.Sprintf("%s+%d", offsetExpr, field.EnumType.Size)
			} else {
				offsetEnd = fmt.Sprintf("%s+4", offsetExpr)
			}
		}
	}

	switch field.Type {
	case parser.TypeBool:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = %s[%s] != 0\n", targetVar, dataVar, offsetStart))
	case parser.TypeUint32:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = d.endian.Uint32(%s[%s:%s])\n", targetVar, dataVar, offsetStart, offsetEnd))
	case parser.TypeInt32:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = int32(d.endian.Uint32(%s[%s:%s]))\n", targetVar, dataVar, offsetStart, offsetEnd))
	case parser.TypeUint64:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = d.endian.Uint64(%s[%s:%s])\n", targetVar, dataVar, offsetStart, offsetEnd))
	case parser.TypeInt64:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = int64(d.endian.Uint64(%s[%s:%s]))\n", targetVar, dataVar, offsetStart, offsetEnd))
	case parser.TypeFloat:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = math.Float32frombits(d.endian.Uint32(%s[%s:%s]))\n", targetVar, dataVar, offsetStart, offsetEnd))
	case parser.TypeDouble:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = math.Float64frombits(d.endian.Uint64(%s[%s:%s]))\n", targetVar, dataVar, offsetStart, offsetEnd))
	case parser.TypeString:
		sb.WriteString(baseIndent + fmt.Sprintf("\t%s = %s.decodeString(%s[%s:%s])\n", targetVar, g.helpersVarName, dataVar, offsetStart, offsetEnd))
	case parser.TypeEnum:
		if field.EnumType != nil && field.EnumType.Size == 1 {
			sb.WriteString(baseIndent + fmt.Sprintf("\t%s = int32(%s[%s])\n", targetVar, dataVar, offsetStart))
		} else {
			sb.WriteString(baseIndent + fmt.Sprintf("\t%s = int32(d.endian.Uint32(%s[%s:%s]))\n", targetVar, dataVar, offsetStart, offsetEnd))
		}
	}
}

func (g *GoGenerator) generateEncoder(sb *strings.Builder, msg *parser.Message, layout *analyzer.MessageLayout, layouts map[string]*analyzer.MessageLayout, byteOrder string) {
	encoderName := fmt.Sprintf("%sEncoder", msg.Name)

	sb.WriteString(fmt.Sprintf("// %s encodes JSON to binary data\n", encoderName))
	sb.WriteString(fmt.Sprintf("type %s struct {\n", encoderName))
	sb.WriteString("\tendian binary.ByteOrder\n")
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("// New%s creates a new encoder\n", encoderName))
	sb.WriteString(fmt.Sprintf("func New%s() *%s {\n", encoderName, encoderName))
	sb.WriteString(fmt.Sprintf("\treturn &%s{\n", encoderName))
	sb.WriteString(fmt.Sprintf("\t\tendian: %s,\n", byteOrder))
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// Encode method
	sb.WriteString(fmt.Sprintf("// Encode encodes JSON string to binary data\n"))
	sb.WriteString(fmt.Sprintf("func (e *%s) Encode(msg []byte) ([]byte, error) {\n", encoderName))
	sb.WriteString("\tdata := make(map[string]any)\n\n")
	sb.WriteString(fmt.Sprintf("\tif err := json.Unmarshal(msg, &data); err != nil {\n"))
	sb.WriteString("\t\treturn nil, err\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString(fmt.Sprintf("\tbuffer := make([]byte, %s)\n", g.constants[msg.Name+"Size"]))

	// Handle union discriminator
	if msg.Union && layout.HasDiscriminator {
		sb.WriteString("\n\t// Union discriminator\n")
		sb.WriteString("\tif len(data) != 1 {\n")
		sb.WriteString("\t\t// only one variant is allowed in a union\n")
		sb.WriteString("\t\treturn nil, errors.New(\"invalid union\")\n")
		sb.WriteString("\t}\n\n")
		sb.WriteString("\tfor name, value := range data {\n")
		sb.WriteString("\t\tswitch name {\n")

		for _, fieldLayout := range layout.Fields {
			fieldName := toCamelCase(fieldLayout.Field.Name)

			sb.WriteString(fmt.Sprintf("\t\tcase \"%s\":\n", fieldName))
			sb.WriteString(fmt.Sprintf("\t\t\tbuffer[%d] = %d\n\n", layout.DiscriminatorOffset, fieldLayout.Field.Number))

			g.generateFieldEncoder(sb, fieldLayout, layouts, "data", "buffer", 0)
		}

		sb.WriteString("\t\tdefault:\n")
		sb.WriteString("\t\t\treturn nil, fmt.Errorf(\"invalid union variant: %s\", name)\n")
		sb.WriteString("\t\t}\n\n")
		sb.WriteString("\t\t// ensure the loop only runs once\n")
		sb.WriteString("\t\tbreak\n")
		sb.WriteString("\t}\n\n")
		sb.WriteString("\treturn buffer, nil\n")
		sb.WriteString("}\n\n")

		return
	}

	// Encode fields (non-union)
	for _, fieldLayout := range layout.Fields {
		sb.WriteString("\n")
		g.generateFieldEncoder(sb, fieldLayout, layouts, "data", "buffer", 0)
	}

	// Encode oneofs
	for _, oneofLayout := range layout.Oneofs {
		oneofName := toCamelCase(oneofLayout.Oneof.Name)

		sb.WriteString(fmt.Sprintf("\n\t// Oneof %s\n", oneofLayout.Oneof.Name))
		sb.WriteString(fmt.Sprintf("\tif %sData, %sOk := data[\"%s\"].(map[string]any); %sOk && len(%sData) == 1 {\n",
			oneofLayout.Oneof.Name, oneofLayout.Oneof.Name, oneofName, oneofLayout.Oneof.Name, oneofLayout.Oneof.Name))
		sb.WriteString("\t\t// only one variant is allowed in a oneof\n")
		sb.WriteString(fmt.Sprintf("\t\tfor key, _ := range %sData {\n", oneofLayout.Oneof.Name))
		sb.WriteString("\t\t\tswitch key {\n")

		for _, variantLayout := range oneofLayout.Fields {
			variantName := toCamelCase(variantLayout.Field.Name)

			sb.WriteString(fmt.Sprintf("\t\t\tcase \"%s\":\n", variantName))
			sb.WriteString(fmt.Sprintf("\t\t\t\tbuffer[%d] = %d\n\n", oneofLayout.DiscriminatorOffset, variantLayout.Field.Number))

			g.generateFieldEncoder(sb, variantLayout, layouts, oneofLayout.Oneof.Name+"Data", "buffer", 3)

			sb.WriteString("\n")
		}

		sb.WriteString("\t\t\tdefault:\n")
		sb.WriteString("\t\t\t\treturn nil, fmt.Errorf(\"invalid oneof variant: %s\", key)\n")
		sb.WriteString("\t\t\t}\n\n")
		sb.WriteString("\t\t// ensure the loop only runs once\n")
		sb.WriteString("\t\tbreak\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t}\n")
	}

	sb.WriteString("\n\treturn buffer, nil\n")
	sb.WriteString("}\n\n")
}

func (g *GoGenerator) generateFieldEncoder(sb *strings.Builder, fieldLayout *analyzer.FieldLayout, layouts map[string]*analyzer.MessageLayout, dataVar, bufferVar string, depth int) {
	baseIndent := strings.Repeat("\t", depth)

	field := fieldLayout.Field
	offset := fieldLayout.Offset
	fieldName := toCamelCase(field.Name)

	if field.Repeated {
		// Handle arrays
		elemSize := fieldLayout.Size / field.ArraySize

		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s (field %d, size %d, array)\n", field.Name, field.Number, field.ArraySize))
		sb.WriteString(baseIndent + fmt.Sprintf("\tif %sData, %sOk := %s[\"%s\"].([]any); %sOk {\n", field.Name, field.Name, dataVar, fieldName, field.Name))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tfor i, elem := range %sData {\n", field.Name))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\tif i >= %d {\n", field.ArraySize))
		sb.WriteString(baseIndent + "\t\t\t\tbreak\n")
		sb.WriteString(baseIndent + "\t\t\t}\n\n")

		// Encode element based on type
		if field.Type == parser.TypeMessage && field.MessageType != nil {
			elemMapName := fmt.Sprintf("%sElemMap", fieldName)

			sb.WriteString(baseIndent + fmt.Sprintf("\t\t\tif %s, %sOk := elem.(map[string]any); %sOk {\n", elemMapName, elemMapName, elemMapName))

			nestedLayout := layouts[field.MessageType.Name]

			for i, nestedField := range nestedLayout.Fields {
				if i != 0 {
					sb.WriteString("\n")
				}

				g.generateFieldEncoder(sb, nestedField, layouts, elemMapName, bufferVar, depth+1)
			}

			sb.WriteString(baseIndent + "\t\t\t}\n")
		} else {
			sb.WriteString(baseIndent + fmt.Sprintf("\t\t\telemOffset := %d + (i * %d)\n\n", offset, elemSize))

			g.generatePrimitiveEncoder(sb, field, "elemOffset", "elem", baseIndent+"\t\t")
		}

		sb.WriteString(baseIndent + "\t\t}\n")
		sb.WriteString(baseIndent + "\t}\n")
	} else if field.Type == parser.TypeMessage && field.MessageType != nil {
		// Nested message
		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s (field %d)\n", field.Name, field.Number))
		sb.WriteString(baseIndent + fmt.Sprintf("\tif %sData, %sOk := %s[\"%s\"].(map[string]any); %sOk {\n", field.Name, field.Name, dataVar, fieldName, field.Name))

		nestedLayout := layouts[field.MessageType.Name]

		for i, nestedField := range nestedLayout.Fields {
			if i != 0 {
				sb.WriteString("\n")
			}

			// Adjust nested field offset to be absolute (parent offset + nested offset)
			adjustedField := &analyzer.FieldLayout{
				Field:  nestedField.Field,
				Offset: offset + nestedField.Offset,
				Size:   nestedField.Size,
			}

			g.generateFieldEncoder(sb, adjustedField, layouts, fmt.Sprintf("%sData", field.Name), bufferVar, depth+1)
		}

		sb.WriteString(baseIndent + "\t}\n")
	} else {
		// Primitive type
		sb.WriteString(baseIndent + fmt.Sprintf("\t// %s (field %d)\n", field.Name, field.Number))
		sb.WriteString(baseIndent + fmt.Sprintf("\tif v, vOk := %s[\"%s\"]; vOk {\n", dataVar, fieldName))

		g.generatePrimitiveEncoder(sb, field, fmt.Sprintf("%d", offset), "v", baseIndent+"\t")

		sb.WriteString(baseIndent + "\t}\n")
	}
}

func (g *GoGenerator) generatePrimitiveEncoder(sb *strings.Builder, field *parser.Field, offsetExpr, valueVar string, baseIndent string) {
	switch field.Type {
	case parser.TypeBool:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif boolVal, ok := %s.(bool); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\tif boolVal {\n"))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\t\tbuffer[%s] = 1\n", offsetExpr))
		sb.WriteString(baseIndent + "\t\t\t}\n")
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeUint32:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint32(buffer[%s:%s+4], uint32(numVal))\n", offsetExpr, offsetExpr))
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeInt32:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint32(buffer[%s:%s+4], uint32(int32(numVal)))\n", offsetExpr, offsetExpr))
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeUint64:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint64(buffer[%s:%s+8], uint64(numVal))\n", offsetExpr, offsetExpr))
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeInt64:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint64(buffer[%s:%s+8], uint64(int64(numVal)))\n", offsetExpr, offsetExpr))
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeFloat:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint32(buffer[%s:%s+4], math.Float32bits(float32(numVal)))\n", offsetExpr, offsetExpr))
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeDouble:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint64(buffer[%s:%s+8], math.Float64bits(numVal))\n", offsetExpr, offsetExpr))
		sb.WriteString(baseIndent + "\t\t}\n")
	case parser.TypeString:
		sb.WriteString(baseIndent + fmt.Sprintf("\t\tif strVal, ok := %s.(string); ok {\n", valueVar))
		sb.WriteString(baseIndent + fmt.Sprintf("\t\t\tcopy(buffer[%s:%s+%d], %s.encodeString(strVal, %d))\n", offsetExpr, offsetExpr, field.StringSize, g.helpersVarName, field.StringSize))
		sb.WriteString(baseIndent + "\t\t}\n")

	case parser.TypeEnum:
		size := uint32(4)

		if field.EnumType != nil {
			size = field.EnumType.Size
		}

		if size == 1 {
			sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
			sb.WriteString(baseIndent + fmt.Sprintf("\t\t\tbuffer[%s] = uint8(numVal)\n", offsetExpr))
			sb.WriteString(baseIndent + "\t\t}\n")
		} else if size == 2 {
			sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
			sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint16(buffer[%s:%s+2], uint16(numVal))\n", offsetExpr, offsetExpr))
			sb.WriteString(baseIndent + "\t\t}\n")
		} else {
			sb.WriteString(baseIndent + fmt.Sprintf("\t\tif numVal, ok := %s.(float64); ok {\n", valueVar))
			sb.WriteString(baseIndent + fmt.Sprintf("\t\t\te.endian.PutUint32(buffer[%s:%s+4], uint32(numVal))\n", offsetExpr, offsetExpr))
			sb.WriteString(baseIndent + "\t\t}\n")
		}
	}
}

func (g *GoGenerator) generateHelpers(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// %s scope for helper functions\n", g.helpersName))
	sb.WriteString(fmt.Sprintf("type %s struct{}\n\n", g.helpersName))
	sb.WriteString("var (\n")
	sb.WriteString(fmt.Sprintf("\t%s = %s{}\n", g.helpersVarName, g.helpersName))
	sb.WriteString(")\n\n")
	sb.WriteString("// decodeString extracts a null-terminated string from fixed-size buffer\n")
	sb.WriteString(fmt.Sprintf("func (%s) decodeString(data []byte) string {\n", g.helpersName))
	sb.WriteString("\t// Find null terminator\n")
	sb.WriteString("\tnullIdx := -1\n\n")
	sb.WriteString("\tfor i, b := range data {\n")
	sb.WriteString("\t\tif b == 0 {\n")
	sb.WriteString("\t\t\tnullIdx = i\n")
	sb.WriteString("\t\t\tbreak\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tif nullIdx == -1 {\n")
	sb.WriteString("\t\t// No null terminator, use entire buffer\n")
	sb.WriteString("\t\treturn string(data)\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\treturn string(data[:nullIdx])\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// encodeString writes a string to fixed-size buffer with null termination\n")
	sb.WriteString(fmt.Sprintf("func (%s) encodeString(str string, size int) []byte {\n", g.helpersName))
	sb.WriteString("\tbuf := make([]byte, size)\n\n")
	sb.WriteString("\t// Truncate if necessary, leave room for null terminator\n")
	sb.WriteString("\tmaxLen := size - 1\n\n")
	sb.WriteString("\tif len(str) > maxLen {\n")
	sb.WriteString("\t\tstr = str[:maxLen]\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tcopy(buf, []byte(str))\n\n")
	sb.WriteString("\t// buf is zero-initialized, so null terminator already in place\n")
	sb.WriteString("\treturn buf\n")
	sb.WriteString("}\n")
}

//
//func (g *GoGenerator) generateRegistry(sb *strings.Builder, schema *parser.Schema, layouts map[string]*analyzer.MessageLayout, byteOrder string) {
//	// Generate registry struct and interfaces
//	sb.WriteString("// MessageRegistry manages message encoding/decoding by ID\n")
//	sb.WriteString("type MessageRegistry struct {\n")
//	sb.WriteString("\tdecoders      map[uint32]MessageDecoder\n")
//	sb.WriteString("\tencoders      map[uint32]MessageEncoder\n")
//	sb.WriteString("\tnames         map[uint32]string\n")
//	sb.WriteString("\tids           map[string]uint32\n")
//	sb.WriteString("\tmessageIdSize uint32\n")
//	sb.WriteString("\tendian        binary.ByteOrder\n")
//	sb.WriteString("}\n\n")
//
//	sb.WriteString("// MessageDecoder interface for message decoders\n")
//	sb.WriteString("type MessageDecoder interface {\n")
//	sb.WriteString("\tDecode([]byte) (string, error)\n")
//	sb.WriteString("}\n\n")
//
//	sb.WriteString("// MessageEncoder interface for message encoders\n")
//	sb.WriteString("type MessageEncoder interface {\n")
//	sb.WriteString("\tEncode(map[string]any) ([]byte, error)\n")
//	sb.WriteString("}\n\n")
//
//	// Generate registry constructor
//	sb.WriteString("// NewMessageRegistry creates a registry for message ID dispatching\n")
//	sb.WriteString("func NewMessageRegistry() *MessageRegistry {\n")
//	sb.WriteString("\tregistry := &MessageRegistry{\n")
//	sb.WriteString("\t\tdecoders:      make(map[uint32]MessageDecoder),\n")
//	sb.WriteString("\t\tencoders:      make(map[uint32]MessageEncoder),\n")
//	sb.WriteString("\t\tnames:         make(map[uint32]string),\n")
//	sb.WriteString("\t\tids:           make(map[string]uint32),\n")
//	sb.WriteString(fmt.Sprintf("\t\tmessageIdSize: %d,\n", schema.MessageIdSize))
//	sb.WriteString(fmt.Sprintf("\t\tendian:        %s,\n", byteOrder))
//	sb.WriteString("\t}\n\n")
//
//	for _, msg := range schema.Messages {
//		layout := layouts[msg.Name]
//		if layout.HasMessageId {
//			sb.WriteString(fmt.Sprintf("\t// Register %s (ID: %d)\n", msg.Name, layout.MessageId))
//			sb.WriteString(fmt.Sprintf("\tregistry.decoders[%d] = New%sDecoder()\n", layout.MessageId, msg.Name))
//			sb.WriteString(fmt.Sprintf("\tregistry.encoders[%d] = New%sEncoder()\n", layout.MessageId, msg.Name))
//			sb.WriteString(fmt.Sprintf("\tregistry.names[%d] = \"%s\"\n", layout.MessageId, msg.Name))
//			sb.WriteString(fmt.Sprintf("\tregistry.ids[\"%s\"] = %d\n\n", msg.Name, layout.MessageId))
//		}
//	}
//
//	sb.WriteString("\treturn registry\n")
//	sb.WriteString("}\n\n")
//
//	// Generate DecodeById method
//	sb.WriteString("// DecodeById decodes a message by reading its ID from the buffer header\n")
//	sb.WriteString("func (r *MessageRegistry) DecodeById(data []byte) (string, string, error) {\n")
//	sb.WriteString("\tif len(data) < int(r.messageIdSize) {\n")
//	sb.WriteString("\t\treturn \"\", \"\", fmt.Errorf(\"buffer too small for message ID: got %d, need at least %d\", len(data), r.messageIdSize)\n")
//	sb.WriteString("\t}\n\n")
//
//	sb.WriteString("\t// Read message ID based on size\n")
//	sb.WriteString("\tvar messageId uint32\n")
//	sb.WriteString("\tswitch r.messageIdSize {\n")
//	sb.WriteString("\tcase 1:\n")
//	sb.WriteString("\t\tmessageId = uint32(data[0])\n")
//	sb.WriteString("\tcase 2:\n")
//	sb.WriteString("\t\tmessageId = uint32(r.endian.Uint16(data[0:2]))\n")
//	sb.WriteString("\tcase 4:\n")
//	sb.WriteString("\t\tmessageId = r.endian.Uint32(data[0:4])\n")
//	sb.WriteString("\tcase 8:\n")
//	sb.WriteString("\t\tmessageId = uint32(r.endian.Uint64(data[0:8]))\n")
//	sb.WriteString("\tdefault:\n")
//	sb.WriteString("\t\treturn \"\", \"\", fmt.Errorf(\"invalid message ID size: %d\", r.messageIdSize)\n")
//	sb.WriteString("\t}\n\n")
//
//	sb.WriteString("\tdecoder, ok := r.decoders[messageId]\n")
//	sb.WriteString("\tif !ok {\n")
//	sb.WriteString("\t\treturn \"\", \"\", fmt.Errorf(\"unknown message ID: %d\", messageId)\n")
//	sb.WriteString("\t}\n\n")
//
//	sb.WriteString("\tmessageName := r.names[messageId]\n")
//	sb.WriteString("\t// Strip message ID header and decode the message body\n")
//	sb.WriteString("\tresult, err := decoder.Decode(data[r.messageIdSize:])\n")
//	sb.WriteString("\treturn messageName, result, err\n")
//	sb.WriteString("}\n\n")
//
//	// Generate GetNameById method
//	sb.WriteString("// GetNameById returns the message name for a given ID\n")
//	sb.WriteString("func (r *MessageRegistry) GetNameById(id uint32) (string, bool) {\n")
//	sb.WriteString("\tname, ok := r.names[id]\n")
//	sb.WriteString("\treturn name, ok\n")
//	sb.WriteString("}\n\n")
//
//	// Generate GetIdByName method
//	sb.WriteString("// GetIdByName returns the message ID for a given name\n")
//	sb.WriteString("func (r *MessageRegistry) GetIdByName(name string) (uint32, bool) {\n")
//	sb.WriteString("\tid, ok := r.ids[name]\n")
//	sb.WriteString("\treturn id, ok\n")
//	sb.WriteString("}\n\n")
//}
